# Bun Test Configuration for Originals Explorer

[test]
# Test runner configuration
preload = []
root = "."

# Coverage configuration
coverage = true
coverageThreshold = 80
coverageDir = "./coverage"

# Test timeout (ms)
timeout = 30000

# Environment
env = { NODE_ENV = "test", DID_DOMAIN = "localhost:5000" }

# Test patterns
include = [
  "**/__tests__/**/*.test.ts",
  "**/__tests__/**/*.test.tsx",
  "**/server/__tests__/**/*.test.ts",
  "**/client/**/__tests__/**/*.test.tsx"
]

exclude = [
  "node_modules",
  "dist",
  "build",
  ".next"
]
