import type { Proof } from './credentials';
import type { ExternalSigner } from './common';

/**
 * Multi-signature policy defining m-of-n threshold requirements.
 * Used to specify how many signatures are needed from a set of authorized signers.
 */
export interface MultiSigPolicy {
  /** Minimum number of signatures required (m in m-of-n) */
  required: number;
  /** Total number of authorized signers (n in m-of-n) */
  total: number;
  /** Verification method IDs of all authorized signers */
  signerVerificationMethods: string[];
  /** Optional timelock: signatures are only valid after this ISO timestamp */
  timelockStart?: string;
  /** Optional timelock: signatures expire after this ISO timestamp */
  timelockEnd?: string;
}

/**
 * A single signature contribution from one participant in a multi-sig flow.
 */
export interface SignatureContribution {
  /** The proof generated by this signer */
  proof: Proof;
  /** Index of the signer in the policy's signerVerificationMethods array */
  signerIndex: number;
  /** Timestamp when this signature was created */
  signedAt: string;
}

/**
 * Options for creating a multi-sig signed credential.
 */
export interface MultiSigSignOptions {
  /** The multi-sig policy governing this signing */
  policy: MultiSigPolicy;
  /** Private keys indexed by verification method ID */
  privateKeys?: Map<string, string>;
  /** External signers indexed by verification method ID */
  externalSigners?: Map<string, ExternalSigner>;
}

/**
 * Result of multi-sig verification.
 */
export interface MultiSigVerificationResult {
  /** Whether the threshold requirement was met */
  verified: boolean;
  /** The policy that was verified against */
  policy: MultiSigPolicy;
  /** Number of valid signatures found */
  validSignatures: number;
  /** Verification method IDs that provided valid signatures */
  validSigners: string[];
  /** Verification method IDs that provided invalid signatures */
  invalidSigners: string[];
  /** Errors encountered during verification */
  errors: string[];
  /** Whether the timelock constraints were satisfied */
  timelockValid?: boolean;
}

/**
 * A pending multi-sig session that collects signatures over time.
 */
export interface MultiSigSession {
  /** Unique session identifier */
  id: string;
  /** The multi-sig policy for this session */
  policy: MultiSigPolicy;
  /** The unsigned document being signed */
  document: Record<string, unknown>;
  /** Collected signature contributions so far */
  contributions: SignatureContribution[];
  /** Session creation timestamp */
  createdAt: string;
  /** Session expiration timestamp (defaults to policy timelockEnd or 24h) */
  expiresAt: string;
  /** Current session status */
  status: 'collecting' | 'threshold_met' | 'expired' | 'finalized';
}

/**
 * Options for escrow-style multi-sig where a third party holds release authority.
 */
export interface EscrowPolicy extends MultiSigPolicy {
  /** Verification method ID of the escrow agent */
  escrowAgent: string;
  /** Conditions under which the escrow agent should release (human-readable) */
  releaseConditions: string;
  /** Whether the escrow agent's signature is mandatory (not counted toward threshold) */
  escrowSignatureRequired: boolean;
}

/**
 * Corporate ownership policy with role-based signing requirements.
 */
export interface CorporatePolicy extends MultiSigPolicy {
  /** Role assignments for each signer */
  roles: Map<string, string>;
  /** Roles whose signature is mandatory regardless of threshold */
  mandatoryRoles?: string[];
}
