/**
 * The concrete browser Turnkey client for Track B signing. Isolated from
 * ./turnkey-session (which stays pure/testable) because @turnkey/sdk-browser
 * pulls a browser-only dependency graph that must not load under `bun test`.
 *
 * The session credential is a NON-EXTRACTABLE P-256 CryptoKey generated by
 * `crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'}, false, …)` and
 * held in IndexedDB by Turnkey's own `TurnkeyIndexedDbClient`. Page script can
 * ask it for a signature but can never read the private scalar out — which is
 * why the credential may survive a reload at all. No raw private key is ever
 * generated, stored, or sent anywhere.
 */
import { Turnkey, type TurnkeyIndexedDbClient } from '@turnkey/sdk-browser';
import { SignatureFormat } from '@turnkey/sdk-types';
import { OTP_LOGIN_SIGNATURE_FORMAT } from './turnkey-session';
import type { SessionKeySigner, TurnkeyRevocationApi } from './turnkey-session';

const TURNKEY_API_BASE_URL = 'https://api.turnkey.com';

/**
 * Cross-check the contract stated in ./turnkey-session against Turnkey's own
 * enum. A renamed member stops resolving; a changed value fails this
 * assignment. Either way the typecheck breaks here instead of the signature
 * silently reverting to DER and signing failing in production again.
 */
const _rawIsStillRaw: typeof OTP_LOGIN_SIGNATURE_FORMAT = SignatureFormat.Raw;
void _rawIsStillRaw;

/**
 * The session key plus the client that stamps with it. `signer` is the only
 * way to reach the key; `clear()` destroys it (sign-out).
 */
export interface SessionKeyHandle {
  signer: SessionKeySigner;
  client: TurnkeyIndexedDbClient;
  clear(): Promise<void>;
}

/**
 * Build the IndexedDB-backed client. It must come from the SDK wrapper rather
 * than `new TurnkeyIndexedDbClient(...)`: only the wrapper attaches the
 * IndexedDbStamper that owns the non-extractable key.
 */
function indexedDbClient(subOrgId: string): Promise<TurnkeyIndexedDbClient> {
  return new Turnkey({
    apiBaseUrl: TURNKEY_API_BASE_URL,
    defaultOrganizationId: subOrgId,
  }).indexedDbClient();
}

/**
 * Open the browser's session key, creating a non-extractable one if this
 * browser has none. `subOrgId` may be '' when the key is minted BEFORE OTP
 * verification — the public key has to exist first so verify-otp can bind the
 * verification token to it. Every request is stamped with the same IndexedDB
 * key regardless of which client instance issues it.
 */
export async function openSessionKey(subOrgId = ''): Promise<SessionKeyHandle> {
  return handleFor(subOrgId, { reset: false });
}

/** Mint a FRESH non-extractable key, discarding any key this browser held. */
export async function resetSessionKey(subOrgId = ''): Promise<SessionKeyHandle> {
  return handleFor(subOrgId, { reset: true });
}

/**
 * Open the IndexedDB client and wrap it as a handle. The two exported entry
 * points differ only in whether the existing key is discarded first; keeping
 * one body means the signer shape cannot drift between them.
 */
async function handleFor(subOrgId: string, opts: { reset: boolean }): Promise<SessionKeyHandle> {
  const client = await indexedDbClient(subOrgId);
  await client.init();
  if (opts.reset) await client.resetKeyPair();
  const publicKeyHex = await client.getPublicKey();
  if (!publicKeyHex) throw new Error('Could not open a browser signing key.');
  return {
    client,
    signer: {
      publicKeyHex,
      // The format is passed, never defaulted: the stamper's default is DER
      // and Turnkey verifies OTP_LOGIN's clientSignature as raw IEEE-P1363,
      // so omitting it produces a signature the API rejects. crypto.subtle
      // hashes SHA-256 internally; the private key is never materialised.
      sign: (message: string) => client.sign(message, SignatureFormat.Raw),
    },
    clear: () => client.clear(),
  };
}

/** The same client, narrowed to what sign-out needs to revoke the key. */
export function asRevocationApi(client: unknown): TurnkeyRevocationApi {
  return client as TurnkeyRevocationApi;
}
